export class ArticleItemBean {
  apkLink:string=''
  author: string = ''
  chapterId = 0
  chapterName: string = ''
  isCollect = false
  courseId = 0
  desc: string = ''
  envelopePic: string = ''
  id = 0
  originId = -1 // 收藏文章列表里面的原始文章id
  link: string = ''
  niceDate: string = ''
  origin: string = ''
  projectLink: string = ''
  publishTime = 0
  title: string = ''
  visible = 0
  zan = 0
  isFresh = false
  isShowImage = true
}
